import Head from "next/head";
import { useState } from "react";
import { Header } from "~/components/Header";
import { Quiz } from "~/components/Quiz";
import { Button } from "~/components/ui/Button";
import { QuizProvider } from "~/context/QuizProvider";

import { api } from "~/utils/api";

export default function Home() {
  const [quizStarted, setQuizStarted] = useState(false);

  const handleStartQuiz = () => {
    setQuizStarted(true);
  };

  const handleCloseQuiz = () => {
    setQuizStarted(false);
  };

  return (
    <>
      <Head>
        <title>Qual filme assistir?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex min-h-screen flex-col items-center justify-center gap-24 bg-gradient-to-b from-[#2c2c2c] to-background p-4 text-white">
        {!quizStarted ? (
          <>
            <div className="flex flex-col gap-2 text-center">
              <h2 className="text-2xl font-bold">
                Chega de passar horas navegando sem encontrar o filme ideal
              </h2>

              <h3 className="text-lg font-light">
                Sugestões com base nos seus gostos pessoais e sem excesso de
                informação
              </h3>
            </div>

            <Button onClick={handleStartQuiz} size="md">
              Iniciar quiz
            </Button>
          </>
        ) : (
          <QuizProvider closeQuiz={handleCloseQuiz}>
            <Quiz />
          </QuizProvider>
        )}
      </main>
    </>
  );
}
